version: '3.8'
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=medical_appointment_booking_db
      - MYSQL_ROOT_PASSWORD=trung2011@vd
    ports:
      - '3307:3306'
    expose:
      - 3306

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql
      # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080
    expose:
      - 8080

  nginx:
    image: nginx:1.27.3
    ports:
      - 80:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

# docker compose -p medical_appointment up -d
